### ISSUE TITLE
Code Samples and Database

### ISSUE THREAD

**Issue by jbeidleman** [MicrosoftLearning/dp-080-Transact-SQL#1]
# Module: 01 (or more?)
#### Step: 00

The SQL query is not valid for AdventureWorksLT ( the database script provided). The course notes have too many AdventureWorks queries.  All examples in PowerPoint/Skillpipe, Demos, and Labs should use the AdventureWorksLT database so students and instructors can run them in what is deemed the course database.

In Mod 1 Slide 9, Current Query:
SELECT OrderDate, COUNT(OrderID) AS Orders
FROM Sales.SalesOrder
WHERE Status = 'Shipped'
GROUP BY OrderDate
HAVING COUNT(OrderID) > 1
ORDER BY OrderDate DESC;

Suggest changing to (it is basically same query just fixed table and columns names):
SELECT OrderDate, COUNT(SalesOrderID) AS Orders
FROM SalesLT.SalesOrderHeader
WHERE Status = 5
GROUP BY OrderDate
HAVING COUNT(SalesOrderID) > 1
ORDER BY OrderDate DESC;

Slide 10, uses Production.Product ( this is from AdventureWorks)
Change the table reference to SalesLT.Product for all 3 queries.

I am sure I will find more through out the course.

**Comment by GraemeMalcolm** [comment]
The sides are not restricted to the course database - they're just example code. You can use the demo scripts (or create your own) if you want to show actual running code, but the code samples on the slides and in the workbook are just that - syntax examples.
