### ISSUE TITLE
Parens and TOP

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/dp-080-Transact-SQL#23]
### Task: Restrict results using TOP

It is best practice to always use parens with the TOP clause.

Replace multiple instances of:

````sql
SELECT TOP 20 Name, ListPrice
````

With:

````sql
SELECT TOP (20) Name, ListPrice
````

Links:
[docs.microsoft.com](https://docs.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql?view=sql-server-ver16#compatibility-support)
[SQL Prompt](https://www.red-gate.com/hub/product-learning/sql-prompt/sql-prompt-code-analysis-avoiding-old-style-top-clause)

**Comment by JulianePadrao** [comment]
This bug has been addressed.

Thanks for your feedback.
