### ISSUE TITLE
Replace AdventureWorks with AdventureWorksLT

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/dp-080-Transact-SQL#24]
"We'll use the AdventureWorks database in this lab, so let's start by exploring it in Azure Data Studio."

I know it's a little thing, but this is bugging me. We are not using the **AdventureWorks** database; we are using the **AdventureWorksLT** database.

**Comment by GraemeMalcolm** [comment]
It's the LT schema, but the database is called adventureworks.
