### ISSUE TITLE
Inconsistent syntax

### ISSUE THREAD

**Issue by username1001** [MicrosoftLearning/dp-080-Transact-SQL#30]
## Lab/Demo: 3a

Exercise - Query multiple tables with joins

### Description of issue

I noticed `AS` is sometimes capitalized, while other times it isn't. 

For example:

```sql
SELECT p.Name As ProductName, c.Name AS Category
FROM SalesLT.Product AS p
JOIN SalesLT.ProductCategory As c
    ON p.ProductCategoryID = c.ProductCategoryID;
```

I know it doesn't make a difference in regards to running the code, but should it be consistent? Is there a reason it isn't? (I'm just learning SQL, so really don't know).

**Comment by GraemeMalcolm** [comment]
It shouldn't matter, but feel free to submit a PR.

**Comment by username1001** [comment]
Yeah, I thought so. Was curious if there was a reason for it. Thank you, @GraemeMalcolm !
