### ISSUE TITLE
Lab 07-Challenge 01: SalesLT.Employee table is missing in the AdventureWorks database

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/dp-080-Transact-SQL#37]
# Module: 07
### Challenge: 01

**Description of issue:**

Unable to find **SalesLT.Employee** table in the **AdventureWorks** database, please see the screenshot below

**Screenshots:**
![image](https://github.com/user-attachments/assets/5fee08fc-5977-4462-b541-c2004c274bdb)
![image](https://github.com/user-attachments/assets/7e770cb1-2c0d-4350-8f52-91c1ae4ec0a0)

**Comment by GraemeMalcolm** [comment]
Looks like they missed this table out of the Azure sample DB. I updated to remove that challenge

**Comment by KashifKhaan** [comment]
Thanks @GraemeMalcolm!
